services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
          VITE_BACKEND_ENDPOINT: <PUBLIC_NLB_DNS_NAME>:5000
          VITE_SERVER_HOSTNAME: ${HOSTNAME}
    ports:
      - 3000:3000
    restart: always

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - frontend
    restart: always
