name: Update backend

on:
    push:
        paths:
            - 'backend-instance/**'

jobs:
    Spin-up-NAT-instance:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            repository: jbetueldev/terraforms
            path: './mern-app'
        
        - name: Check files
          run: ls
        
        - name: Terraform apply
          run: |
            cd mern-app
            terraform apply -target=aws_instance.nat_instance -auto-approve
            terraform apply -target=aws_route.outbound_nat_route -auto-approve
    
    Update-the-code-in-backend-instance:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            path: './backend-instance'
        
        - name: Check files
          run: ls
          