name: Update in backend-instance

on: push
    # push:
    #     paths:
    #         - 'backend-instance/**'

jobs:
    Spin-up-NAT-instance:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          with:
            repository: jbetueldev/terraforms
        - uses: hashicorp/setup-terraform@v3

        - name: Check files
          run: ls
        
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4.0.2
          with:
            aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws-region: us-east-1

        - name: Terraform apply 
          run: | 
            cd mern-app
            ls
            terraform init
            terraform apply -target=aws_instance.nat_instance -auto-approve
            terraform apply -target=aws_route.outbound_nat_route -auto-approve
            terraform output -raw nat_instance_ip > nat.txt
            export NAT_IP=$(xargs <nat.txt)
            echo $NAT_IP
        
        - name: SSH connect
          env:
              aws-key-pair: ${{secrets.AWS_KEY_PAIR}}
              nat-ip: $NAT_IP
          run: |
            echo "$aws-key-pair" > key_pair && chmod 400 key_pair
            ssh -o StrictHostKeyChecking=no -i key_pair ec2-user@$nat-ip '
      
                echo "This is a test file." > test.txt
    
                '
    
    Update-the-code-in-backend-instance:
        runs-on: ubuntu-latest
        needs: Spin-up-NAT-instance
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            path: './backend-instance'
        
        - name: Check files
          run: ls
    
    # Connect-to-backend-instance-1:
    #     runs-on: ubuntu-latest
    #     needs: Update-the-code-in-backend-instance
    #     steps:
    #     - name: SSH connect
    #       env:
    #           aws-key-pair: ${{secrets.AWS_KEY_PAIR}}
    #       run: |
    #         echo "$aws-key-pair" > key_pair && chmod 400 key_pair
    #         ssh -o StrictHostKeyChecking=no -i key_pair ec2-user@$NAT_IP '
      
    #             echo "This is a test file." > test.txt
    
    #             '