name: Update backend

on: push
    # push:
    #     paths:
    #         - 'backend-instance/**'

jobs:
    Spin-up-NAT-instance:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          with:
            repository: jbetueldev/terraforms
            path: './mern-app'
        - uses: hashicorp/setup-terraform@v3

        - name: Check files
          run: ls
        
        - name: Setup AWS credentials
          env:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          run: |
            mkdir ~/.aws
            echo "$aws_access_key_id" >> ~/.aws/credentials
            echo "$aws_secret_access_key" >> ~/.aws/credentials 
        
        - name: Terraform apply 
          run: | 
            cd mern-app
            terraform init
            terraform apply -target=aws_instance.nat_instance -auto-approve
            terraform apply -target=aws_route.outbound_nat_route -auto-approve 
    
    Update-the-code-in-backend-instance:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            path: './backend-instance'
        
        - name: Check files
          run: ls
