name: Update in backend

on:
    push:
        paths:
            - 'backend-instance/**'

env:
    AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
    AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
    DEPLOY_SSH_KEY: ${{secrets.AWS_KEY_PAIR}}
    DEPLOY_SCRIPT: |
        if [ ! -d "/home/ec2-user/mern-gallery-sample-app" ]; then
            git clone git@github.com:jbetueldev/mern-gallery-sample-app.git
        else
            cd /home/ec2-user/mern-gallery-sample-app/backend-instance
            docker stop backend
            docker rm backend
            docker rmi mern-backend:latest
            git pull origin main
        fi
        cd /home/ec2-user/mern-gallery-sample-app/backend-instance
        docker buildx build -t mern-backend:latest .
        docker run --name backend -p 5000:5000 -d --restart always mern-backend:latest
        docker logs backend

jobs:
    Initialization:
        runs-on: ubuntu-latest
        outputs:
          output1: ${{steps.nat.outputs.nat_ip}}
        steps:
        - name: Checkout terraform repo
          uses: actions/checkout@v4
          with:
            repository: jbetueldev/terraforms

        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v3
        
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4.0.2
          with:
            aws-access-key-id: $AWS_ACCESS_KEY_ID
            aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
            aws-region: $AWS_DEFAULT_REGION
        
        - name: Spin up NAT-instance
          id: nat
          run: | 
            cd mern-app
            ls
            terraform init
            terraform destroy -target=aws_instance.nat_instance -auto-approve
            terraform apply -target=aws_instance.nat_instance -auto-approve
            terraform apply -target=aws_route.outbound_nat_route -auto-approve
            terraform output -raw nat_instance_ip
            echo "nat_ip=$(terraform output -raw nat_instance_ip)" >> "$GITHUB_OUTPUT"
        
        - name: Set up NAT-instance as jump host
          env:
              NAT_IP: ${{steps.nat.outputs.nat_ip}}
          run: |
            echo "$DEPLOY_SSH_KEY" > private_key && chmod 400 private_key
            scp -o StrictHostKeyChecking=no -i private_key /home/runner/work/mern-gallery-sample-app/mern-gallery-sample-app/private_key ec2-user@$NAT_IP:~/

    Update_backend_instance-1:
        runs-on: ubuntu-latest
        needs: Initialization
        steps:
        - name: Get backend-instance-1 Private IP address
          id: ip_address
          run: |
            sudo apt-get install jq
            export INSTANCE_IP=$(aws ec2 describe-instances --output json --filters "Name=tag:Name,Values=backend-instance-1" | jq ".Reservations[].Instances[].PrivateIpAddress" | tr -d '"')
            echo "INSTANCE_IP=$INSTANCE_IP"
            echo "INSTANCE_IP=$INSTANCE_IP" >> "$GITHUB_OUTPUT"

        - name: Connect to NAT-instance > backend-instance-1
          env:
              NAT_IP: ${{needs.Initialization.outputs.output1}}
              INSTANCE_IP: ${{steps.ip_address.outputs.INSTANCE_IP}}
          run: |
            echo "$DEPLOY_SSH_KEY" > private_key && chmod 400 private_key
            ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o ServerAliveCountMax=4 -i private_key ec2-user@$NAT_IP -t "
            ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o ServerAliveCountMax=4 -i private_key ec2-user@${INSTANCE_IP} -t '
            ${DEPLOY_SCRIPT}
            '"

    Update_backend_instance-2:
        runs-on: ubuntu-latest
        needs: Initialization
        steps:
        - name: Get backend-instance-2 Private IP address
          id: ip_address
          run: |
            sudo apt-get install jq
            export INSTANCE_IP=$(aws ec2 describe-instances --output json --filters "Name=tag:Name,Values=backend-instance-2" | jq ".Reservations[].Instances[].PrivateIpAddress" | tr -d '"')
            echo "INSTANCE_IP=$INSTANCE_IP"
            echo "INSTANCE_IP=$INSTANCE_IP" >> "$GITHUB_OUTPUT"

        - name: Connect to NAT-instance > backend-instance-2
          env:
              NAT_IP: ${{needs.Initialization.outputs.output1}}
              INSTANCE_IP: ${{steps.ip_address.outputs.INSTANCE_IP}}
          run: |
            echo "$DEPLOY_SSH_KEY" > private_key && chmod 400 private_key
            ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o ServerAliveCountMax=4 -i private_key ec2-user@$NAT_IP -t "
            ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o ServerAliveCountMax=4 -i private_key ec2-user@${INSTANCE_IP} -t '
            ${DEPLOY_SCRIPT}
            '"

    Update_backend_instance-3:
        runs-on: ubuntu-latest
        needs: Initialization
        steps:
        - name: Get backend-instance-3 Private IP address
          id: ip_address
          run: |
            sudo apt-get install jq
            export INSTANCE_IP=$(aws ec2 describe-instances --output json --filters "Name=tag:Name,Values=backend-instance-3" | jq ".Reservations[].Instances[].PrivateIpAddress" | tr -d '"')
            echo "INSTANCE_IP=$INSTANCE_IP"
            echo "INSTANCE_IP=$INSTANCE_IP" >> "$GITHUB_OUTPUT"

        - name: Connect to NAT instance > backend-instance-3
          env:
              NAT_IP: ${{needs.Initialization.outputs.output1}}
              INSTANCE_IP: ${{steps.ip_address.outputs.INSTANCE_IP}}
          run: |
            echo "$DEPLOY_SSH_KEY" > private_key && chmod 400 private_key
            ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o ServerAliveCountMax=4 -i private_key ec2-user@$NAT_IP -t "
            ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o ServerAliveCountMax=4 -i private_key ec2-user@${INSTANCE_IP} -t '
            ${DEPLOY_SCRIPT}
            '"