name: Update backend

on:
    push:
        paths:
            - 'backend-instance/**'

jobs:
    Spin-up-NAT-instance:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            repository: jbetueldev/terraforms
            path: './mern-app'
        
        - name: Check files
          run: ls
        
        - name: Terraform apply
          env:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          run: |
            cd mern-app
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            echo "$aws_access_key_id" >> ~/.aws/credentials
            echo "$aws_secret_access_key" >> ~/.aws/credentials 
            terraform init
            terraform apply -target=aws_instance.nat_instance -auto-approve
            terraform apply -target=aws_route.outbound_nat_route -auto-approve
    
    Update-the-code-in-backend-instance:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            path: './backend-instance'
        
        - name: Check files
          run: ls
