name: Update backend

on: push
    # push:
    #     paths:
    #         - 'backend-instance/**'

jobs:
    Spin-up-NAT-instance:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          with:
            repository: jbetueldev/terraforms
        - uses: hashicorp/setup-terraform@v3

        - name: Check files
          run: ls
        
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4.0.2
          with:
            aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws-region: us-east-1
        
        # - name: Set up AWS key pair and Github SSH key
        #   run: |
        #     cd mern-app
        #     echo "$AWS_KEY_PAIR" > MERN.pem && chmod 400 MERN.pem
        #     echo "$SSH_KEY_GITHUB" > id_rsa && chmod 400 id_rsa

        - name: Terraform apply 
          run: | 
            cd mern-app
            ls
            terraform init
            terraform apply -target=aws_instance.nat_instance -auto-approve
            terraform apply -target=aws_route.outbound_nat_route -auto-approve 
    
    Update-the-code-in-backend-instance:
        runs-on: ubuntu-latest
        needs: Spin-up-NAT-instance
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            path: './backend-instance'
        
        - name: Check files
          run: ls
